version: "3.8"

services:
  inatel-app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: .docker/entrypoint.sh
    env_file:
      - ./.env
    depends_on:
      - inatel-postgres-db
    networks:
      - inatel-network
    ports:
      - 8000:8000
    volumes:
      - .:/var/www

  inatel-postgres-db:
    image: postgres:alpine
    volumes:
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=inatel_db:inateluser:12345678,inatel_log_db:inateluser:12345678
      - POSTGRES_USER=inateluser
      - POSTGRES_PASSWORD=12345678
    ports:
      - 5432:5432
    networks:
      - inatel-network

volumes:
  postgres_data:

networks:
  inatel-network: