# Generated by Django 4.0.2 on 2022-02-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportWorkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('registration', models.CharField(max_length=64, verbose_name='matrícula')),
            ],
            options={
                'verbose_name': 'técnico',
                'verbose_name_plural': 'técnicos',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, verbose_name='descrição')),
                ('date', models.DateTimeField(verbose_name='data e hora')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technician')),
            ],
            options={
                'verbose_name': 'agendamento de trabalho',
                'verbose_name_plural': 'agendamentos de trabalho',
            },
        ),
        migrations.CreateModel(
            name='ImportInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_work_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.importworkfile')),
            ],
        ),
    ]
