# Generated by Django 4.0.2 on 2022-02-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleWorkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Importação de escalas de trabalho',
                'verbose_name_plural': 'Importações de escalas de trabalho',
            },
        ),
        migrations.CreateModel(
            name='ScheduleWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=127)),
                ('technician_register', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scheduleworkfile')),
            ],
            options={
                'verbose_name': 'Escala de Trabalho',
                'verbose_name_plural': 'Escalas de Trabalho',
            },
        ),
    ]
