# Generated by Django 4.0.2 on 2022-02-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='technician',
        ),
        migrations.RenameModel(
            old_name='ImportWorkFile',
            new_name='ScheduleWorkFile',
        ),
        migrations.DeleteModel(
            name='ImportInformation',
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
        migrations.AddField(
            model_name='schedulework',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scheduleworkfile'),
        ),
    ]
