# Generated by Django 4.0.2 on 2022-02-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulework',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
