# Generated by Django 4.0.2 on 2022-02-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schedulework_is_valid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulework',
            options={'verbose_name': 'Escala de Trabalho', 'verbose_name_plural': 'Escalas de Trabalho'},
        ),
        migrations.AlterModelOptions(
            name='scheduleworkfile',
            options={'verbose_name': 'Importação de escalas de trabalho', 'verbose_name_plural': 'Importações de escalas de trabalho'},
        ),
        migrations.RemoveField(
            model_name='schedulework',
            name='is_valid',
        ),
    ]
