# Generated by Django 4.0.2 on 2022-02-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100, null=True)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('response_code', models.PositiveSmallIntegerField()),
                ('method', models.CharField(max_length=10, null=True)),
                ('remote_address', models.CharField(max_length=20, null=True)),
                ('exec_time', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('body_response', models.TextField()),
                ('body_request', models.TextField()),
            ],
        ),
    ]
