# Generated by Django 4.0.2 on 2022-02-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.AddField(
            model_name='log',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
